CREATE DATABASE Mensageria;

USE Mensageria;

CREATE TABLE [TBL_PAGINA](
  [PAG_ID] [int] IDENTITY(1,1) NOT NULL,
  [PAG_IP] [varchar](255) NULL,
  [PAG_NOME_PAGINA] [varchar](255) NULL,
  [PAG_BROWSER] [varchar](255) NULL,
  PRIMARY KEY ([PAG_ID]),
);

CREATE TABLE [TBL_PARAMETRO](
  [PAR_ID] [int] IDENTITY(1,1) NOT NULL,
  [PAG_ID] [int]  NULL,
  [PAR_NOME] [varchar](255) NULL,
  [PAR_VALOR] [varchar](255) NULL,
  PRIMARY KEY ([PAR_ID]),
  CONSTRAINT FK_TBL_PAGINA_TBL_PARAMETRO FOREIGN KEY ([PAG_ID]) REFERENCES TBL_PAGINA([PAG_ID])
);
